### ISSUE TITLE
Update LineUp to v4.0.0-alpha.10

### ISSUE THREAD

**Issue by thinkh** [datavisyn/tdp_core#150]
After successfully integrating LineUp v4.0.0-alpha.9 (see #138) we should update to most recent release [v4.0.0-alpha.10](https://github.com/lineupjs/lineupjs/releases/tag/v4.0.0-alpha.10).

**Comment by sgratzl** [comment]
This is still an alpha release which is buggy and might change till the final release.

**Comment by thinkh** [comment]
Yes, the most critical one I discovered so far: TDP/Ordino + Lineup v4.0.0-alpha.10 does not compile with Typescript 2.7.2 anymore. Hence, we must update the whole TDP/Ordino/Phovea to Typescript 3.1+ in order to use Lineup 4.

**Comment by thinkh** [comment]
I switched (manually) to Typescript 3.2.2 for my workspace and fixed some compile errors.
I committed my changes to the branch `thinkh/test-lineup4-alpha.10, since the switch to TS 3.2 requires also changes in other repos and documented some reasons for changes in the commit messages.

Here are some compile errors that I could not fix so far:

```
ERROR in /ordino/tdp_core/src/lineup/ARankingView.ts(195,46):
TS2339: Property 'v' does not exist on type 'IGroupItem'.
ERROR in /ordino/tdp_core/src/lineup/ARankingView.ts(195,54):
TS2339: Property 'i' does not exist on type 'IGroupItem'.
ERROR in /ordino/tdp_core/src/lineup/internal/cmds.ts(7,23):
TS2724: Module '"../../../../node_modules/lineupjs/src"' has no exported member 'createMappingFunction'. Did you mean 'IColorMappingFunction'?
ERROR in /ordino/tdp_core/src/lineup/internal/column.ts(4,37):
TS2724: Module '"../../../../node_modules/lineupjs/src"' has no exported member 'ScaleMappingFunction'. Did you mean 'IColorMappingFunction'?
ERROR in D:/dev/repos/phovea/ordino2/tdp_core/src/lineup/internal/column.ts(4,143):
TS2724: Module '"../../../../node_modules/lineupjs/src"' has no exported member 'toCategories'. Did you mean 'Categories'?
ERROR in /ordino/tdp_core/src/lineup/internal/column.ts(85,12):
TS2339: Property 'setSplicer' does not exist on type 'NumbersColumn'.
```

* I don't know how `IGroupItem` changed and what/how to use instead?
* The missing `ScaleMappingFunction` and `createMappingFunction` is reported in https://github.com/lineupjs/lineupjs/issues/128.
* After refactoring `toCategories` is [defined as internal](https://github.com/lineupjs/lineupjs/blob/develop/src/model/internalCategorical.ts#L7-L20)
* `setSplicer` might be solvable similar to https://github.com/lineupjs/lineupjs/issues/124

**Comment by thinkh** [comment]
Meeting notes:

* GroupItem do not contain the data itself anymore, but an index that can then be used to retrieve the data from the data provider (`.getIndex()`).
* Some events have been removed in LineUp 4 which will **break** the provenance graph. Hence, a list of events from both version is required. Further, we need an _adapter_ that prevents the provenance graph from breaking.
* Building the _tdp_core_ test branch with TS 2.7.2 works, expect the errors posted (above)[https://github.com/datavisyn/tdp_core/issues/150#issuecomment-452705895]

**Comment by thinkh** [comment]
Outdated, since LineUp v4 is added as dependency from the `lineupjs/lineupjs#lineup-v4` branch in tdp_core:

https://github.com/datavisyn/tdp_core/blob/6581047b02e4c5ac1c8f968e64641c0f93716a27/package.json#L81
